#
server:
  #address: 127.0.0.1
  port: 7070
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-nginx
  main:
    web-application-type: servlet
    banner-mode: console
